# Generated by Django 4.2.6 on 2023-11-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInfomation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('birth', models.DateField(null=True)),
                ('avatar', models.BinaryField(null=True)),
                ('role', models.CharField(blank=True, choices=[('customer', 'Customer'), ('seller', 'Seller'), ('supplier', 'Supplier')], max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
