# Generated by Django 4.2.6 on 2023-12-25 11:02

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(null=True)),
                ('product_id', models.BigIntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'shipping_carts',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(null=True)),
                ('product_id', models.BigIntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(null=True)),
                ('create_at', models.DateField(null=True)),
                ('method', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'order_payment',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('voucher_discount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('voucher_id', models.BigIntegerField(null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        
        migrations.CreateModel(
            name='ReviewInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(null=True)),
                ('product_id', models.BigIntegerField(null=True)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('comment_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ShippingRiceiveInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(null=True)),
                ('recipient_name', models.CharField(max_length=255, null=True)),
                ('recipient_adress', models.CharField(max_length=255, null=True)),
                ('recipient_phone', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'shipping_info',
            },
        ),
        migrations.CreateModel(
            name='ShippingScheduleInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(null=True)),
                ('schedule_time', models.DateTimeField(null=True)),
                ('schedule', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'shipping_schedule',
            },
        ),
        migrations.CreateModel(
            name='ShopInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('user_id', models.BigIntegerField(null=True)),
                ('logo', models.ImageField(null=True, upload_to='shop_logos/')),
            ],
            options={
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='VoucherInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, null=True)),
                ('discount_type', models.CharField(max_length=10, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('total_quantity', models.IntegerField(null=True)),
                ('used_quantity', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'vouchers',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
