# Generated by Django 4.2.6 on 2024-01-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('cat_id', models.BigIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('sold', models.IntegerField(null=True)),
                ('shop_id', models.BigIntegerField(null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('image', models.URLField(max_length=500, null=True)),
                ('images', models.JSONField(null=True)),
                ('historical_sold', models.IntegerField(null=True)),
                ('liked_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
